export const MARK_MINE = 'MARK_MINE'

export const UNMARK_MINE = 'UNMARK_MINE'

export const RESET_MINE_NUM = 'RESET_MINE_NUM'

export const WAIT_RESULT = 'WAIT_RESULT'

export const RESET_RESULT = 'RESET_RESULT'

export const SEND_FAIL_RESULT = 'SEND_FAIL_RESULT'

export const SEND_WIN_RESULT = 'SEND_WIN_RESULT'

export const SET_GAME_GRADE = 'SET_GAME_GRADE'

export const TOGGLE_PLAYING_STATUS = 'TOGGLE_PLAYING_STATUS'

export const RESET_GAME = 'RESET_GAME'

export const START_GAME = 'START_GAME'
